/**
 * Seed Script: 50 Properties Across Azuay Province
 *
 * Creates realistic test properties in:
 * - Cuenca (main city, 35 properties)
 * - Gualaceo (8 properties)
 * - Paute (4 properties)
 * - Azogues (3 properties)
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding 50 properties across Azuay province...");

  // Find or create test agents
  let agent1 = await prisma.user.findFirst({
    where: { role: "AGENT" },
  });

  if (!agent1) {
    agent1 = await prisma.user.create({
      data: {
        email: "agent1@inmoapp.com",
        name: "Carlos Inmobiliario",
        role: "AGENT",
        phone: "+593 99 123 4567",
      },
    });
    console.log("✅ Created agent:", agent1.email);
  }

  // Create second agent
  let agent2 = await prisma.user.findFirst({
    where: { email: "agent2@inmoapp.com" },
  });

  if (!agent2) {
    agent2 = await prisma.user.create({
      data: {
        email: "agent2@inmoapp.com",
        name: "María Propiedades",
        role: "AGENT",
        phone: "+593 98 987 6543",
      },
    });
    console.log("✅ Created agent:", agent2.email);
  }

  const agentIds = [agent1.id, agent2.id];

  // Real coordinates for Azuay neighborhoods
  const properties = [
    // CUENCA - CENTER & HISTORIC ZONE (5 properties)
    {
      title: "Casa colonial restaurada Centro Histórico",
      description:
        "Hermosa casa colonial con patio interno, perfecta para inversión turística",
      price: 220000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 4,
      bathrooms: 3,
      area: 200,
      address: "Calle Hermano Miguel y Bolívar",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010101",
      latitude: -2.9005,
      longitude: -79.0035,
    },
    {
      title: "Suite amoblada Centro Histórico",
      description: "Suite completamente equipada con wifi y servicios",
      price: 550,
      transactionType: "RENT" as const,
      category: "SUITE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 50,
      address: "Calle Larga 5-40",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010101",
      latitude: -2.901,
      longitude: -79.004,
    },
    {
      title: "Departamento Centro Cuenca",
      description: "Apartamento moderno con balcón y vista al Tomebamba",
      price: 110000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 95,
      address: "Av. Gran Colombia",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010102",
      latitude: -2.8995,
      longitude: -79.005,
    },
    {
      title: "Local comercial Centro",
      description: "Local de esquina con alto tráfico comercial",
      price: 1500,
      transactionType: "RENT" as const,
      category: "COMMERCIAL" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 2,
      area: 110,
      address: "Calle Bolívar y Mariano Cueva",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010101",
      latitude: -2.9015,
      longitude: -79.0045,
    },
    {
      title: "Penthouse Remigio Crespo",
      description: "Exclusivo penthouse de 2 plantas con terraza panorámica",
      price: 280000,
      transactionType: "SALE" as const,
      category: "PENTHOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 3.5,
      area: 250,
      address: "Av. Remigio Crespo Toral",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010104",
      latitude: -2.9115,
      longitude: -79.0095,
    },

    // CUENCA - EL EJIDO (5 properties)
    {
      title: "Casa moderna El Ejido",
      description: "Casa contemporánea con acabados de lujo, 3 garajes",
      price: 195000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2.5,
      area: 180,
      address: "Av. 12 de Abril y Calle Larga",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010150",
      latitude: -2.8995,
      longitude: -79.0044,
    },
    {
      title: "Departamento El Ejido arriendo",
      description: "Apartamento nuevo con piscina y área de recreación",
      price: 850,
      transactionType: "RENT" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 95,
      address: "Sector El Ejido",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010150",
      latitude: -2.9,
      longitude: -79.005,
    },
    {
      title: "Villa en El Ejido con piscina",
      description: "Hermosa villa con piscina, sauna y jardín amplio",
      price: 340000,
      transactionType: "SALE" as const,
      category: "VILLA" as const,
      status: "AVAILABLE" as const,
      bedrooms: 4,
      bathrooms: 3.5,
      area: 380,
      address: "Av. España y 12 de Abril",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010151",
      latitude: -2.8985,
      longitude: -79.0055,
    },
    {
      title: "Duplex El Ejido",
      description: "Dúplex de 2 plantas con independencia total",
      price: 165000,
      transactionType: "SALE" as const,
      category: "DUPLEX" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 130,
      address: "Calle Las Monjas",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010150",
      latitude: -2.899,
      longitude: -79.004,
    },
    {
      title: "Loft moderno El Ejido",
      description: "Loft con techos altos, diseño industrial, apto negocio",
      price: 78000,
      transactionType: "RENT" as const,
      category: "LOFT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 75,
      address: "Calle Tarqui",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010150",
      latitude: -2.9005,
      longitude: -79.0048,
    },

    // CUENCA - YANUNCAY & TOTORACOCHA (6 properties)
    {
      title: "Casa Yanuncay nueva",
      description:
        "Casa nueva en zona residencial tranquila con acceso a servicios",
      price: 145000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 120,
      address: "Sector Yanuncay",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010107",
      latitude: -2.8875,
      longitude: -79.0125,
    },
    {
      title: "Departamento Yanuncay con vista",
      description: "Moderno departamento con vista panorámica y balcón",
      price: 98000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 85,
      address: "Av. Ordóñez Lasso",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010107",
      latitude: -2.8875,
      longitude: -79.0125,
    },
    {
      title: "Casa arriendo Totoracocha",
      description: "Casa familiar ideal para familia grande, zona verde",
      price: 750,
      transactionType: "RENT" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 4,
      bathrooms: 2.5,
      area: 170,
      address: "Totoracocha Alto",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010108",
      latitude: -2.88,
      longitude: -79.014,
    },
    {
      title: "Departamento Totoracocha",
      description: "Apartamento con servicios completos y piscina",
      price: 125000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 120,
      address: "Av. Totoracocha",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010108",
      latitude: -2.881,
      longitude: -79.015,
    },
    {
      title: "Suite Yanuncay amoblada",
      description: "Suite completamente amoblada con acceso a piscina",
      price: 600,
      transactionType: "RENT" as const,
      category: "SUITE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 55,
      address: "Calle Principal Yanuncay",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010107",
      latitude: -2.887,
      longitude: -79.012,
    },
    {
      title: "Office Yanuncay",
      description:
        "Oficina profesional en zona comercial, ideal abogados/consultores",
      price: 1100,
      transactionType: "RENT" as const,
      category: "OFFICE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 2,
      area: 95,
      address: "Av. Ordóñez Lasso",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010107",
      latitude: -2.888,
      longitude: -79.013,
    },

    // CUENCA - MONAY & RICAURTE (5 properties)
    {
      title: "Villa de lujo Monay",
      description: "Espectacular villa con jardín amplio, piscina y cancha",
      price: 380000,
      transactionType: "SALE" as const,
      category: "VILLA" as const,
      status: "AVAILABLE" as const,
      bedrooms: 5,
      bathrooms: 4,
      area: 450,
      address: "Sector Monay Golf",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010102",
      latitude: -2.9145,
      longitude: -78.9875,
    },
    {
      title: "Casa Monay elegante",
      description: "Casa elegante en zona exclusiva con acceso a club",
      price: 225000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 3,
      area: 210,
      address: "Av. Monay",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010102",
      latitude: -2.914,
      longitude: -78.988,
    },
    {
      title: "Terreno Ricaurte para construcción",
      description: "Terreno plano de 500m² ideal para vivienda o comercio",
      price: 48000,
      transactionType: "SALE" as const,
      category: "LAND" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 0,
      area: 500,
      address: "Vía a Ricaurte",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010250",
      latitude: -2.8755,
      longitude: -78.9965,
    },
    {
      title: "Casa arriendo Ricaurte",
      description: "Casa amplia en zona tranquila, acceso fácil a Cuenca",
      price: 700,
      transactionType: "RENT" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 160,
      address: "Sector Ricaurte",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010250",
      latitude: -2.876,
      longitude: -78.996,
    },
    {
      title: "Terreno en Ricaurte grande",
      description: "Terreno de 800m² con servicios básicos, ideal desarrollo",
      price: 65000,
      transactionType: "SALE" as const,
      category: "LAND" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 0,
      area: 800,
      address: "Calle Principal Ricaurte",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010251",
      latitude: -2.875,
      longitude: -78.997,
    },

    // CUENCA - MIRAFLORES & BELÉN (6 properties)
    {
      title: "Casa Miraflores tranquila",
      description: "Casa familiar en zona residencial tranquila",
      price: 155000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 140,
      address: "Sector Miraflores",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010105",
      latitude: -2.8945,
      longitude: -79.0155,
    },
    {
      title: "Departamento Miraflores",
      description: "Apartamento moderno con servicios",
      price: 88000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 75,
      address: "Av. Miraflores",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010105",
      latitude: -2.894,
      longitude: -79.016,
    },
    {
      title: "Casa arriendo Miraflores",
      description: "Casa acogedora, perfecta para familia",
      price: 650,
      transactionType: "RENT" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 150,
      address: "Calle Principal Miraflores",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010105",
      latitude: -2.895,
      longitude: -79.015,
    },
    {
      title: "Casa Belén con terraza",
      description: "Casa moderna con terraza y vista",
      price: 175000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2.5,
      area: 155,
      address: "Sector Belén",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010106",
      latitude: -2.892,
      longitude: -79.017,
    },
    {
      title: "Departamento Belén",
      description: "Apartamento con piscina y servicios",
      price: 102000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 90,
      address: "Av. de las Américas",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010106",
      latitude: -2.8925,
      longitude: -79.0175,
    },
    {
      title: "Local comercial Belén",
      description: "Local con buen flujo de clientes",
      price: 1400,
      transactionType: "RENT" as const,
      category: "COMMERCIAL" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 2,
      area: 100,
      address: "Av. Circunvalación",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010106",
      latitude: -2.8915,
      longitude: -79.018,
    },

    // CUENCA - MACHANGARA & ESTADIO (5 properties)
    {
      title: "Casa Machangara nueva",
      description: "Casa nueva en zona en desarrollo",
      price: 135000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 110,
      address: "Sector Machangara",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010109",
      latitude: -2.9075,
      longitude: -79.0215,
    },
    {
      title: "Departamento Machangara",
      description: "Apartamento económico bien ubicado",
      price: 75000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 60,
      address: "Av. Machangara",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010109",
      latitude: -2.908,
      longitude: -79.022,
    },
    {
      title: "Casa Estadio",
      description: "Casa familiar cerca de estadios y parques",
      price: 148000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 125,
      address: "Sector Estadio",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010110",
      latitude: -2.9,
      longitude: -79.02,
    },
    {
      title: "Suite Estadio",
      description: "Suite amoblada con servicios incluidos",
      price: 500,
      transactionType: "RENT" as const,
      category: "SUITE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 48,
      address: "Calle Estadio",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010110",
      latitude: -2.9005,
      longitude: -79.0205,
    },
    {
      title: "Bodega Machangara",
      description: "Bodega con muelle de carga, ideal comercio",
      price: 2500,
      transactionType: "RENT" as const,
      category: "WAREHOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 1,
      area: 250,
      address: "Vía Industrial Machangara",
      city: "Cuenca",
      state: "Azuay",
      zipCode: "010109",
      latitude: -2.907,
      longitude: -79.021,
    },

    // GUALACEO (8 properties)
    {
      title: "Casa Gualaceo centro",
      description: "Casa tradicional en el corazón de Gualaceo",
      price: 95000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 2,
      area: 100,
      address: "Parque Central Gualaceo",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030150",
      latitude: -3.04,
      longitude: -78.96,
    },
    {
      title: "Departamento Gualaceo nuevo",
      description: "Apartamento moderno con vista a la plaza",
      price: 72000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 65,
      address: "Calle Principal Gualaceo",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030150",
      latitude: -3.0405,
      longitude: -78.9605,
    },
    {
      title: "Casa arriendo Gualaceo",
      description: "Casa acogedora para familia, zona tranquila",
      price: 480,
      transactionType: "RENT" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 90,
      address: "Sector Gualaceo Rural",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030151",
      latitude: -3.042,
      longitude: -78.962,
    },
    {
      title: "Terreno Gualaceo agrícola",
      description: "Terreno agrícola de 1000m² con agua, ideal cultivos",
      price: 28000,
      transactionType: "SALE" as const,
      category: "LAND" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 0,
      area: 1000,
      address: "Vía a sector rural",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030152",
      latitude: -3.045,
      longitude: -78.965,
    },
    {
      title: "Villa Gualaceo con huerta",
      description: "Villa con terreno amplio, huerta y jardín",
      price: 145000,
      transactionType: "SALE" as const,
      category: "VILLA" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 200,
      address: "Sector Las Palmas Gualaceo",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030150",
      latitude: -3.038,
      longitude: -78.958,
    },
    {
      title: "Suite Gualaceo turística",
      description: "Suite amoblada, excelente para turismo",
      price: 420,
      transactionType: "RENT" as const,
      category: "SUITE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 45,
      address: "Centro Gualaceo",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030150",
      latitude: -3.04,
      longitude: -78.9605,
    },
    {
      title: "Local comercial Gualaceo",
      description: "Local en zona comercial del centro",
      price: 650,
      transactionType: "RENT" as const,
      category: "COMMERCIAL" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 1,
      area: 70,
      address: "Calle Comercio",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030150",
      latitude: -3.041,
      longitude: -78.961,
    },
    {
      title: "Casa Gualaceo rural",
      description: "Casa en zona rural, con acceso a río",
      price: 75000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 120,
      address: "Sector San Juan Gualaceo",
      city: "Gualaceo",
      state: "Azuay",
      zipCode: "030153",
      latitude: -3.048,
      longitude: -78.97,
    },

    // PAUTE (4 properties)
    {
      title: "Casa Paute valle",
      description: "Casa hermosa en el Valle de Paute",
      price: 110000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 135,
      address: "Paute Centro",
      city: "Paute",
      state: "Azuay",
      zipCode: "030250",
      latitude: -3.2,
      longitude: -78.74,
    },
    {
      title: "Terreno Paute para cultivos",
      description: "Terreno de 1500m² en zona agrícola productiva",
      price: 32000,
      transactionType: "SALE" as const,
      category: "LAND" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 0,
      area: 1500,
      address: "Vía rural Paute",
      city: "Paute",
      state: "Azuay",
      zipCode: "030251",
      latitude: -3.21,
      longitude: -78.75,
    },
    {
      title: "Finca Paute productiva",
      description: "Finca con cultivos establecidos y casa",
      price: 165000,
      transactionType: "SALE" as const,
      category: "FARM" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 3000,
      address: "Sector Bulán Paute",
      city: "Paute",
      state: "Azuay",
      zipCode: "030252",
      latitude: -3.22,
      longitude: -78.76,
    },
    {
      title: "Casa arriendo Paute",
      description: "Casa acogedora en zona tranquila",
      price: 380,
      transactionType: "RENT" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 100,
      address: "Paute Bajo",
      city: "Paute",
      state: "Azuay",
      zipCode: "030250",
      latitude: -3.195,
      longitude: -78.735,
    },

    // AZOGUES (6 properties)
    {
      title: "Casa Azogues céntrica",
      description: "Casa en el centro de Azogues con servicios",
      price: 128000,
      transactionType: "SALE" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 3,
      bathrooms: 2,
      area: 145,
      address: "Centro Azogues",
      city: "Azogues",
      state: "Azuay",
      zipCode: "030101",
      latitude: -2.73,
      longitude: -78.995,
    },
    {
      title: "Departamento Azogues",
      description: "Apartamento moderno en zona comercial",
      price: 68000,
      transactionType: "SALE" as const,
      category: "APARTMENT" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 70,
      address: "Calle Bolívar Azogues",
      city: "Azogues",
      state: "Azuay",
      zipCode: "030101",
      latitude: -2.7305,
      longitude: -78.9955,
    },
    {
      title: "Terreno Azogues",
      description: "Terreno en zona de expansión",
      price: 35000,
      transactionType: "SALE" as const,
      category: "LAND" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 0,
      area: 600,
      address: "Sector expandido Azogues",
      city: "Azogues",
      state: "Azuay",
      zipCode: "030102",
      latitude: -2.735,
      longitude: -79.0,
    },
    {
      title: "Casa arriendo Azogues",
      description: "Casa acogedora en sector residencial",
      price: 520,
      transactionType: "RENT" as const,
      category: "HOUSE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 2,
      bathrooms: 1,
      area: 95,
      address: "Sector Nuevo Azogues",
      city: "Azogues",
      state: "Azuay",
      zipCode: "030103",
      latitude: -2.732,
      longitude: -78.997,
    },
    {
      title: "Suite Azogues turística",
      description: "Suite amoblada con acceso a servicios",
      price: 450,
      transactionType: "RENT" as const,
      category: "SUITE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 1,
      bathrooms: 1,
      area: 50,
      address: "Centro Azogues",
      city: "Azogues",
      state: "Azuay",
      zipCode: "030101",
      latitude: -2.731,
      longitude: -78.996,
    },
    {
      title: "Oficina Azogues profesional",
      description: "Oficina moderna en zona comercial",
      price: 900,
      transactionType: "RENT" as const,
      category: "OFFICE" as const,
      status: "AVAILABLE" as const,
      bedrooms: 0,
      bathrooms: 1,
      area: 80,
      address: "Calle Principal Azogues",
      city: "Azogues",
      state: "Azuay",
      zipCode: "030101",
      latitude: -2.7315,
      longitude: -78.9965,
    },
  ];

  // Assign agents randomly
  const propertiesWithAgent = properties.map((property, index) => ({
    ...property,
    agentId: agentIds[index % agentIds.length],
  }));

  // Clear existing properties (optional - comment out to keep existing)
  await prisma.property.deleteMany({});

  // Create properties
  let created = 0;
  for (const property of propertiesWithAgent) {
    try {
      const createdProperty = await prisma.property.create({
        data: property,
      });
      console.log(
        `✅ ${created + 1}. ${createdProperty.title} (${createdProperty.city})`,
      );
      created++;
    } catch (_error) {
      console.log(
        `⚠️  Property "${property.title}" might already exist, skipping...`,
      );
    }
  }

  console.log("🎉 Seeding complete! Created", created, "properties");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
